### ISSUE TITLE
SQL Error bei langen Texten

### ISSUE THREAD

**Issue by b3z** [trintel/feedback#10]
Wenn man zu langen Text in eine Nachricht schreibt kommt folgender Fehler:

```
2022-11-15 12:36:09.799 ERROR 1 --- [io-8080-exec-22] o.h.engine.jdbc.spi.SqlExceptionHelper   : Value too long for column "MESSAGE VARCHAR(255)": "'Hier kommt mal ein langer Text rein. Hier kommt mal ein langer T…
```

**Comment by Felioh** [comment]
Datenstruktur angepasst. Jetzt sind auch längere Texte in den Descriptions möglich.

**Comment by Felioh** [comment]
![image](https://user-images.githubusercontent.com/18168614/201979955-a2935d02-ee0a-49ed-a643-5526155ed7ad.png)

**Comment by Felioh** [comment]
Die View muss noch entsprechend angepasst werden

**Comment by Bennideluecks** [comment]
Das Problem bezieht sich auch auf die Nachrichten-Felder in den Transaktionen. Dort besteht der Fehler noch (siehe Screenshot.) Hinweis: Da die Uhrzeit noch nicht korrekt dargestellt wird (siehe Issue #9), ist der Fehler in der Log-Datei 1 Stunde später.

<img width="474" alt="Bildschirm­foto 2022-11-15 um 21 59 52" src="https://user-images.githubusercontent.com/95080138/202024418-e6bf3b63-8eec-4abd-870c-5fed1f3d958b.png">

<img width="513" alt="Bildschirm­foto 2022-11-15 um 21 59 23" src="https://user-images.githubusercontent.com/95080138/202024450-d1b3489e-aa6a-47ea-a6f8-937130c3f515.png">

**Comment by Felioh** [comment]
Im Quelltext angepasst. Zum Live-schalten müsste ich allerdings einmal kurz an die laufende Datenbank ran. Das mache ich in einem Zuge mit dem nächsten Upgrade.
