### ISSUE TITLE
Standard Aktionen Bearbeiten Button geht nicht

### ISSUE THREAD

**Issue by b3z** [trintel/feedback#11]
"Man kann std Aktionen nicht bearbeiten."

**Comment by b3z** [comment]
Soll man auch nicht können, sie sind ausgegraut, was aber schwer zu sehen ist.

![Screenshot 2022-11-15 at 15 27 15](https://user-images.githubusercontent.com/47346598/201944159-c2b98eb9-4b20-4714-b98f-0a2ae902ff43.png)

**Comment by b3z** [comment]
Vielleicht sollten wir die Buttons nicht ausgrauen sondern ausblenden. @cwerl

**Comment by cwerl** [comment]
Da kommt immer eigentlich ein Tooltip der erklärt dass das nicht geht, denke nicht dass das missverständlich ist. Wenn ich den Button ganz entferne, ist das nicht mehr einheitlich.

**Comment by b3z** [comment]
Nadann würde ich das mal als Fehler des Nutzers abstempeln und gut ist.
