### ISSUE TITLE
Produkt und Mengenfelder bei einer Anfrage deaktivieren

### ISSUE THREAD

**Issue by Bennideluecks** [trintel/feedback#12]
Produkt und Mengenfelder bei einer Anfrage sollen gelöscht oder zumindest ausgeblendet oder deaktiviert werden. Eine Anfrage besteht aus vielen Positionen, weshalb ein einziges Feld nicht zielführend ist. Anstelle dessen ist ein (verpflichtender) Dateiupload sinnvoll, beispielsweise eine Anfrage als PDF-Datei.

<img width="499" alt="Bildschirm­foto 2022-11-15 um 15 55 20" src="https://user-images.githubusercontent.com/95080138/201951185-49bf144d-8f4b-4368-9898-407ad0c0e3b7.png">

**Comment by cwerl** [comment]
Das Produktfeld würde ich lassen, da ja das Produkt übersichtshalber bei der Transaktion angezeigt wird. Ich könnte aber das Mengenfeld entfernen und den Dateiupload verpflichtend machen.

**Comment by b3z** [comment]
Dann könnte man bei Produkt sowas wie “Office Ausstattung” hinschreiben. Und später bei Preis die Summe der Positionen.

**Comment by Bennideluecks** [comment]
Bitte gerne folgende Änderung vornehmen: 
Das Produkt-Feld in "Betreff" (engl. subject) ändern, damit es für die Übersicht in der Transaktion erhalten bleibt, aber als "Produkt-Feld" verschwindet. Das Mengenfeld dann bitte entfernen oder auf unsichtbar schalten.

**Comment by b3z** [comment]
Verstehe ich richtig, dass das nur eine Namensänderung ist. Richtig?

**Comment by Bennideluecks** [comment]
Ja, die Namensänderung reicht.

**Comment by Bennideluecks** [comment]
Bei mir steht immer noch "Produkt" und nicht "Betreff". Getestet mit Safari, Firefox und Chrome. Cookies und temp. Dateien habe ich auch gelöscht.

**Comment by b3z** [comment]
Haben wir auf dem Schirm. 👍
