### ISSUE TITLE
Sprache anpassen

### ISSUE THREAD

**Issue by KrasRBZWirtschaftKiel** [trintel/feedback#14]
Der Begriff "Transactions" ist den Schülern fremd. Besser wäre "Ein- und Verkauf". 

Kann man aus der Sicht einzelner Länder definieren, ob die Unternehmen entweder Kunden oder Lieferanten sind? Also: für Deutsche Unternehmen sind die Dänen Kunden und die Norweger Lieferanten, für Dänische Unternehmen sind die Deutschen Unternehmen Lieferanten, während die Niederländer Kunden sind, ...

Man müsste dann als Lehrer im Admin - Panel festlegen, wer an wen verkauft. 

Dann könnte bei der Auswahl von Unternehmen einer Ländergruppe eine bestimmte Auswahl an Transaktionen erfolgen. Das macht es u.U. für Schüler übersichtlicher.

Unternehmen, die weder Lieferant noch Kunden sind, werden für die Schüler eines Landes ausgeblendet. Das macht es bei größeren Planspielen für die Schüler übersichtlicher.

**Comment by b3z** [comment]
>  Der Begriff "Transactions" ist den Schülern fremd. Besser wäre "Ein- und Verkauf”.

Stellt man die App auf Deutsch, so heißt das Feld “Transaktionen”. Ist nur der Fakt, dass das Wort in Englisch ist, das Problem?

>  Kann man aus der Sicht einzelner Länder definieren, ob die Unternehmen entweder Kunden oder Lieferanten sind? Also: für Deutsche Unternehmen sind die Dänen Kunden und die Norweger Lieferanten, für Dänische Unternehmen sind die Deutschen Unternehmen Lieferanten, während die Niederländer Kunden sind, ...

Das hatte @Bennideluecks auch schon einmal angesprochen. Dieses Feature ist, wenn ich mich richtig entsinne, vorerst ein “nice to have”.

**Comment by KrasRBZWirtschaftKiel** [comment]
> > Der Begriff "Transactions" ist den Schülern fremd. Besser wäre "Ein- und Verkauf”.
> 
> Stellt man die App auf Deutsch, so heißt das Feld “Transaktionen”. Ist nur der Fakt, dass das Wort in Englisch ist, das Problem?
> 

_nein, der Begriff an sich. "Ein- und Verkauf" sind wesentliche Begriffe aus der kaufm. Ausbildung und darum geht es hier ja such eigentlich. Um einzelne Ein- und Verkäufe.

Außerdem haben es auch mit einem hohen Anteil von Schülern mit Migrationshintergrund zu tun. Da ist einfache Sprache gefragt._

> > Kann man aus der Sicht einzelner Länder definieren, ob die Unternehmen entweder Kunden oder Lieferanten sind? Also: für Deutsche Unternehmen sind die Dänen Kunden und die Norweger Lieferanten, für Dänische Unternehmen sind die Deutschen Unternehmen Lieferanten, während die Niederländer Kunden sind, ...
> 
> Das hatte @Bennideluecks auch schon einmal angesprochen. Dieses Feature ist, wenn ich mich richtig entsinne, vorerst ein “nice to have”. 

_richtig_

**Comment by Felioh** [comment]
@KrasRBZWirtschaftKiel Das ist ein relativ einfacher fix. Hier hatten wit Benjamin mal eine Datei gegeben, die alle "Textfelder" der Website enthält (Gedacht für die Sprachunterstützung)
Dort könnt ihr aber natürlich alles rein schreiben. Transactions können wir ersetzen zu "Purchases and sales".
Schaut doch bitte nochmal drüber, ob nochwas angepasst werden könnte ("Transactions" taucht ja mehrmals auf und da hat man alles auf einen Blick ;).
[lang.zip](https://github.com/trintel/feedback/files/10025351/lang.zip)
FYI @b3z @cwerl

**Comment by KrasRBZWirtschaftKiel** [comment]
Ich klicke mich mal mit Benni durch und wir passen die Begriffe an.

**Comment by KrasRBZWirtschaftKiel** [comment]
Wäre es möglich, dass Benni und ich Zugriff im Admin - Panel auf alle Transaktionen bekommen? Ich kann nur die von mir eingerichtete Transaktion bearbeiten.
