### ISSUE TITLE
Produktfeld

### ISSUE THREAD

**Issue by KrasRBZWirtschaftKiel** [trintel/feedback#15]
Ein einzelnes Produktfeld macht beim Planspiel m.E. wenig Sinn. Vielleicht lässt man das erstmal weg und gibt nur ein Feld für die Gesamtsumme der Anfrage, des Angebotes, der Bestellung usw. ein.

Vielleicht wäre es dann im nächsten Schritt möglich ganze Produktlisten zu erstellen. Dann macht es natürlich Sinn, gleich einen Geschäftsbrief von Trintel erstellen zu lassen - und dann ist es natürlich auch sinnvoll ein Warenlager zu haben. Aber vielleicht ist das schon zu viel für eine Verbesserung und eher ein neues Projekt....

**Comment by b3z** [comment]
Das Problem wurde hier (#12) schon einmal angesprochen.

**Comment by Felioh** [comment]
duplicate of #12

**Comment by b3z** [comment]
Plan hier ist, dass die Schüler ein oder mehrere PDF mit Rechnung usw oder Angebot hochladen. Dann die Summe in das bisherige Preis Feld eintragen, Mengen Feld kommt weg (intern default auf 1) und dann rechnen wir in den statistiken nur noch mit der Summe.

**Comment by KrasRBZWirtschaftKiel** [comment]
Moin Luca,
Unsere Email funktioniert leider bis Freitag nicht. Ab dann sind wir hoffentlich wieder erreichbar. ich habe auch keine Ahnung ob meine Mail Dich erreicht.

Zum Update:
Ich stimme überein. Die Summe ist sinnvoll um eine einfache Kalkulation zu erstellen.

Frohes neues Jahr, lieben Dank und Gruß
Matthias

Von meinem iPad gesendet

Am 01.01.2023 um 19:33 schrieb Luca ***@***.***>:

﻿

Plan hier ist, dass die Schüler ein oder mehrere PDF mit Rechnung usw oder Angebot hochladen. Dann die Summe in das bisherige Preis Feld eintragen, Mengen Feld kommt weg (intern default auf 1) und dann rechnen wir in den statistiken nur noch mit der Summe.
