### ISSUE TITLE
Dateianhang von mehreren Dateien

### ISSUE THREAD

**Issue by KrasRBZWirtschaftKiel** [trintel/feedback#16]
Wäre es möglich an Transaktionen mehrere Dateien anzuhängen, im Grunde wie an einer normalen Email? Manche SuS möchten einen Brief und einen Katalog versenden.

**Comment by b3z** [comment]
Jup, geht jetzt. Wenn man im explorer, der beim Upload aufgeht mehrere Dateien auswählt. Unter mac macht man das mit control und clicken. Unter windows geht das wahrscheinlich ähnlich. Dann werden alle pdf angehängt und können einzeln runtergeladen werden.

**Comment by KrasRBZWirtschaftKiel** [comment]
Hi Luca,
vielen Dank! Hatte Benni noch mit Dir wegen des Produktfeldes bei den Aktionen gesprochen? Das sollte nach Möglichkeit ausgeblendet werden und erstmal nicht von den Nutzern ausgefüllt werden müssen, da i.d.R. immer mehrere Produkte ein- oder verkauft werden.

Lieben Dank und Gruß
Matthias

Von: Luca ***@***.***>
Antworten an: trintel/feedback ***@***.***>
Datum: Mittwoch, 1. Februar 2023 um 20:08
An: trintel/feedback ***@***.***>
Cc: Matthias Kraski ***@***.***>, Author ***@***.***>
Betreff: Re: [trintel/feedback] Dateianhang von mehreren Dateien (Issue #16)


Closed #16<https://github.com/trintel/feedback/issues/16> as completed.

**Comment by KrasRBZWirtschaftKiel** [comment]
Hallo Luca,
beim Zugriff auf die Unternehmen (vom Adim – Account und auch vom Schüler Account aus) erscheint eine Fehlermeldung: [Ein Bild, das Text enthält.  Automatisch generierte Beschreibung]

Kannst du das beheben?

Lieben Gruß
Matthias

Von: Luca ***@***.***>
Antworten an: trintel/feedback ***@***.***>
Datum: Mittwoch, 1. Februar 2023 um 20:08
An: trintel/feedback ***@***.***>
Cc: Matthias Kraski ***@***.***>, Author ***@***.***>
Betreff: Re: [trintel/feedback] Dateianhang von mehreren Dateien (Issue #16)


Closed #16<https://github.com/trintel/feedback/issues/16> as completed.

**Comment by b3z** [comment]
Ich kann dir gerade nicht ganz folgen. Wir werden die Datenbank einmal zurücksetzen, sollte das danach immer noch der Fall sein, werden wir uns das nochmal genauer ansehen.
