### ISSUE TITLE
Beschreibung von Unternehmen

### ISSUE THREAD

**Issue by KrasRBZWirtschaftKiel** [trintel/feedback#17]
Das Feld für die Website funktioniert nicht. Man kann nur eine sehr kurze url angeben. 

Können wir Felder für 

- Skype bzw. Telefon
- Emailadresse
- Bankverbindung (IBAN) 
- Land 
Felder haben? Die sollten in der Übersicht dann untereinander dargestellt werden.

**Comment by b3z** [comment]
Das Website Feld wurde mittlerweile repariert. Des Weiteren werden auch mit dem nächsten Update Zeilenumbrüche in der Unternehmenssignatur wahrgenommen. Extra Felder sind notiert.
