### ISSUE TITLE
Parallele Installation

### ISSUE THREAD

**Issue by KrasRBZWirtschaftKiel** [trintel/feedback#19]
In KW7 wollen wir zwei Planspiele parallel laufen lassen. Wäre es möglich Trintel 2 x zu installieren oder einen parallelen Durchlauf zu ermöglichen?

**Comment by b3z** [comment]
Ja, ich denke das wäre machbar.

**Comment by b3z** [comment]
Läuft auf Port 8083 👍 

Beide Instanzen laufen unabhängig voneinander.

**Comment by KrasRBZWirtschaftKiel** [comment]
Prima Luca, das ist hilfreich. So langsam fangen die Schüler an sich zu registrieren und die ersten Unternehmen einzurichten.

Lieben Gruß
Matthias

Von meinem iPhone gesendet

Am 06.02.2023 um 20:38 schrieb Luca ***@***.***>:

﻿

Läuft auf Port 8083 👍

Beide Instanzen laufen unabhängig voneinander.

**Comment by b3z** [comment]
Dann müsst ihr bedenken, dass durch das erstellen der neuen Instanz die alten Links geändert wurden. Für den Fall, dass die Schüler sagen, der alte Link ginge nicht mehr.

**Comment by KrasRBZWirtschaftKiel** [comment]
Hallo Luca und Benni,
Mir ist noch ein kleiner Bug bei Trintel aufgefallen: Ich habe neue Transaktionen bei Trintel eingegeben (Bestellung, Frage, Antwort). Diese Transaktionen werden Schülern aber nicht zur Auswahl angeboten. es wäre schön, wenn wir das noch sehr kurzfristig hinbekommen können. Morgen startet wieder das Planspiel.

Lieben Gruß
Matthias

Von meinem iPad gesendet

Am 06.02.2023 um 20:51 schrieb Matthias Kraski ***@***.***>:

﻿ Prima Luca, das ist hilfreich. So langsam fangen die Schüler an sich zu registrieren und die ersten Unternehmen einzurichten.

Lieben Gruß
Matthias

Von meinem iPhone gesendet

Am 06.02.2023 um 20:38 schrieb Luca ***@***.***>:

﻿

Läuft auf Port 8083 👍

Beide Instanzen laufen unabhängig voneinander.

**Comment by b3z** [comment]
Weiterführung hier https://github.com/trintel/feedback/issues/22On 12. Mar 2023, at 19:59, KrasRBZWirtschaftKiel ***@***.***> wrote:﻿
Hallo Luca und Benni,

Mir ist noch ein kleiner Bug bei Trintel aufgefallen: Ich habe neue Transaktionen bei Trintel eingegeben (Bestellung, Frage, Antwort). Diese Transaktionen werden Schülern aber nicht zur Auswahl angeboten. es wäre schön, wenn wir das noch sehr kurzfristig hinbekommen können. Morgen startet wieder das Planspiel.



Lieben Gruß

Matthias



Von meinem iPad gesendet



Am 06.02.2023 um 20:51 schrieb Matthias Kraski ***@***.***>:



﻿ Prima Luca, das ist hilfreich. So langsam fangen die Schüler an sich zu registrieren und die ersten Unternehmen einzurichten.



Lieben Gruß

Matthias



Von meinem iPhone gesendet



Am 06.02.2023 um 20:38 schrieb Luca ***@***.***>:



﻿



Läuft auf Port 8083 👍



Beide Instanzen laufen unabhängig voneinander.
