### ISSUE TITLE
Spiel importieren und Spiel zurücksetzen funktioniert nicht

### ISSUE THREAD

**Issue by Bennideluecks** [trintel/feedback#20]
Der Export als SQL-Datei eines Spiel funktioniert, allerdings kommt beim Import der Datei folgender Fehler:

<img width="418" alt="Bildschirm­foto 2023-02-02 um 11 46 26" src="https://user-images.githubusercontent.com/95080138/216304860-e71b8fc1-053d-46bf-a273-30b495e996f8.png">

Beim Klicken auf "Spiel zurücksetzen" kommt folgender Fehler:

<img width="489" alt="Bildschirm­foto 2023-02-02 um 11 46 49" src="https://user-images.githubusercontent.com/95080138/216304989-7f462d96-dc62-4f6f-b826-80d56cf70837.png">

**Comment by b3z** [comment]
Wie in meiner Mail schon geschrieben habe ich die DB resettet. Jetzt sollte das Problem behoben sein. Reset vom Panel aus klappt bei mir jetzt. Vielleicht kannst du das verifizieren. Zudem kann es sein, dass die Exporte von einer vorherigen Version Fehler beinhalten, die wir jetzt gefixt haben. Deshalb am besten mit neuen exporten probieren, insofern man nicht auf die alten angewiesen ist. 
Gib mir am besten direkt bescheid, falls da weiter Probleme auftreten.

**Comment by Bennideluecks** [comment]
Ja, Import, Export und Reset funktionieren jetzt bei mir auch, perfekt! Nach jeder dieser Aktionen bekomme ich nur ein "connection refused" als Fehlermeldung angezeigt. Aber bei einem erneuten einloggen ist alles, wie es soll.

Danke!

**Comment by b3z** [comment]
Ja, das hängt damit zusammen, dass der webserver beim Reset neu gestartet wird. Deshalb ist er für ein paar Sekunden nicht erreichbar.
