### ISSUE TITLE
Default-Profilbilder der Unternehmen werde nicht mehr angezeigt

### ISSUE THREAD

**Issue by Bennideluecks** [trintel/feedback#21]
Das Default-Profilbild von Unternehmen wird nicht mehr angezeigt.

<img width="1172" alt="Bildschirm­foto 2023-02-03 um 18 20 25" src="https://user-images.githubusercontent.com/95080138/216667303-2b45af28-fb95-436f-b5de-061a20e43f9d.png">

**Comment by b3z** [comment]
In der 2. Instanz besteht das Problem komischerweise nicht. 
Ich werde mir das nochmal anschauen.

**Comment by b3z** [comment]
Sollte jetzt gelöst sein.
