### ISSUE TITLE
Definierbare Transaktionen nicht sichtbar

### ISSUE THREAD

**Issue by b3z** [trintel/feedback#22]
Hallo Luca und Benni, Mir ist noch ein kleiner Bug bei Trintel aufgefallen: Ich habe neue Transaktionen bei Trintel eingegeben (Bestellung, Frage, Antwort). Diese Transaktionen werden Schülern aber nicht zur Auswahl angeboten. es wäre schön, wenn wir das noch sehr kurzfristig hinbekommen können. Morgen startet wieder das Planspiel. Lieben Gruß Matthias

**Comment by b3z** [comment]
Weiterführung von #19 wir trennen das am liebsten voneinander.

Ich kann das heute mittag mal anschauen. Auf welcher Instanz ist das?

**Comment by KrasRBZWirtschaftKiel** [comment]
http://v12049.1blu.de:8082/

**Comment by b3z** [comment]
Jo, habe ich gesehen. Bin dran.

**Comment by b3z** [comment]
Tatsächlich war ein requirement, dass man nicht mit einer Custom Action anfangen kann. Als zweite action in der Kette funktionieren demnach die Custom Actions (hier als special actions).
![image](https://user-images.githubusercontent.com/47346598/224996119-f4e28d0f-6e9c-4be4-81e9-93814cf63d63.png)

**Comment by KrasRBZWirtschaftKiel** [comment]
Vielen Dank, Luca!

Von meinem iPhone gesendet

Am 14.03.2023 um 13:11 schrieb b3z ***@***.***>:

﻿

Tatsächlich war ein requirement, dass man nicht mit einer Custom Action anfangen kann. Als zweite action in der Kette funktionieren demnach die Custom Actions (hier als special actions).
[image]<https://user-images.githubusercontent.com/47346598/224996119-f4e28d0f-6e9c-4be4-81e9-93814cf63d63.png>
