### ISSUE TITLE
Passwort zurücksetzen funktioniert nicht

### ISSUE THREAD

**Issue by Bennideluecks** [trintel/feedback#23]
Die Funktion "Password zurücksetzen" funktioniert nicht. Bei der Ausführung der Aktion kommt folgende Fehlermeldung:

Sorry, something went wrong!

Mail server connection failed; nested exception is javax.mail.MessagingException: Got bad greeting from SMTP host: w00e2844.kasserver.com, port: 465, response: [EOF]. Failed messages: javax.mail.MessagingException: Got bad greeting from SMTP host: w00e2844.kasserver.com, port: 465, response: [EOF]
State: 500
Time: 2023-11-04 11:36:27.523

**Comment by Felioh** [comment]
@b3z da hing noch dein privater Mailserver hinter, oder?

**Comment by b3z** [comment]
Yep. Schaue ich nachher mal rein.

**Comment by Bennideluecks** [comment]
Gerne kann folgender Mailserver mit der E-Mail Adresse pw@kiel-server.com genutzt werden: 

Mailserver-Benutzername
pw@kiel-server.com

Passwort: 5552!vlwV

Posteingangsserver
mx2f23.netcup.net

Postausgangsserver
mx2f23.netcup.net
(Server erfordert eine Authentifizierung)

Unterstützte eingehende Mail-Protokolle
POP3, IMAP

Unterstützte ausgehende Mail-Protokolle
SMTP

Um eine nicht sichere Verbindung über POP3 herzustellen, verwenden Sie den Port 110.

Um eine nicht sichere Verbindung über IMAP herzustellen, verwenden Sie den Port 143.

Um Nachrichten nicht geschützt über SMTP zu senden, verwenden Sie den Port 25.

**Comment by b3z** [comment]
@Bennideluecks das is super, den kann ich da eintragen. Allerdings ist dieses Github Issue hier öffentlich, deshalb änderst du am besten das oben gesendete Passwort und schickst mir das neue privat per Mail. Gerne auch das von der aktuellen VM.
